### ISSUE TITLE
Unable to forward session in request

### ISSUE THREAD

**Issue by varora1406** [fastify/fastify-secure-session#101]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.24.1

### Plugin version

3.0.0

### Node.js version

14.18.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.0.1

### Description

We are using Twitter Login with Passport (https://github.com/jaredhanson/passport-twitter)
A call is sent to Twitter with session object changes by the aforementioned library, and then when a callback request from Twitter is received at Fastify end, its session object is reset.

I am believing it has to do with fastify-secure-session. More details at https://github.com/jaredhanson/passport-twitter/issues/109

### Steps to Reproduce

Please follow https://github.com/jaredhanson/passport-twitter/issues/109

### Expected Behavior

Session object should not be reset and work properly

**Comment by Eomm** [comment]
Could you add the request's callback details?

- What is the payload?
- Does it contain all the query parameters expected?
- Does it contain the headers?

**Comment by varora1406** [comment]
I am no longer working on this, hence closing this ticket for now
