### ISSUE TITLE
Add support for typed session data

### ISSUE THREAD

**Issue by Moeriki** [fastify/fastify-secure-session#115]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I'd like to type the data I put in and get out of the session.

### Motivation

I don't like type-casting `any` on every `session.get()`.

### Example

```ts
// fastify-secure-session/index.d.ts
export interface Session {
  // …
  get<Key extends keyof SessionData>(key: Key): SessionData[Key] | undefined;
  set<Key extends keyof SessionData>(key: Key, value: SessionData[Key] | undefined): void;
}

export interface SessionData {
  [key: string]: any;
}
```

```ts
# user code
declare module 'fastify-secure-session' {
  interface SessionData {
    codeVerifier: string;
    tokenSet: TokenSet;
  }
}
```

**Comment by climba03003** [comment]
PR is welcome. Remember to add an unit test.
