### ISSUE TITLE
Add method to get all data in session

### ISSUE THREAD

**Issue by CheyenneForbes** [fastify/fastify-secure-session#118]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Other session modules, both for fastify and other libraries, provide a way to get all data from the current session. Some use a dedicated `data()` method or by calling `get()` without a key.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by Fdawgs** [comment]
closed by #124
