### ISSUE TITLE
How do I set the expiration time for a separate Session

### ISSUE THREAD

**Issue by sunbx** [fastify/fastify-secure-session#119]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

It appears that setting an expiration time is globally valid

For example, set an expiration time of 60 seconds
request.session.options({ maxAge:60 })

After 60 seconds, all messages will be cleared. How do I set the expiration time of a KEY by setting a separate KEY?

**Comment by climba03003** [comment]
From what you mention is not how `session` works. 
You need to create your custom application logic to check against the specified `key`, then remove on your own.

**Comment by sunbx** [comment]
> From what you mention is not how `session` works. You need to create your custom application logic to check against the specified `key`, then remove on your own.

Does the library's Session information exist in memory? Or does it exist in a local file? If it exists in a local file where is the path?

**Comment by climba03003** [comment]
> 
> Does the library's Session information exist in memory? Or does it exist in a local file? If it exists in a local file where is the path?

The data is encrypted and stored in `cookies`. No `in-memory` or `database` is needed for this plugin.
