### ISSUE TITLE
Providing an empty array of keys does not throw an error

### ISSUE THREAD

**Issue by antoine-coulon** [fastify/fastify-secure-session#127]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.1

### Plugin version

4.1.1

### Node.js version

16.14.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.5.1

### Description

Hey, 

I'm currently implementing key rotation and I'm not sure if this is a bug or the expected behavior but when providing an empty array of keys in the plugin option `key`, the plugin is not throwing any error in the same way as when an invalid or empty key is provided (as a String or Buffer).

Consequently by providing an empty array of keys the plugin will be registered but will make the `encode` phase fail at runtime when trying to set something on the `secure session`.

For now, the check on Arrays is only about values inside the Array here: https://github.com/fastify/fastify-secure-session/blob/a9998c52b835f3d385f014d5abe1d8051d79d8de/index.js#L68 
When the Array is empty, it seems like no additional check is performed.

### Steps to Reproduce

Take for instance this example which allows the plugin to be registered:

```js
import FastifySecureSession from "@fastify/secure-session";

const fastify = require('fastify')({ logger: false });

fastify.register(FastifySecureSession, {
  cookieName: "session-cookie",
  key: [] // empty array of secret keys,
  cookie: {
    path: "/",
    maxAge: 3600,
    httpOnly: true,
  },
});

fastify.get('/encode', function (request, reply) {
  request.session.set('data', { someData: [] });
  reply.send("encode done");
});

fastify.listen(2000, (err) => {
  if (err) {
    process.exit(1);
  }
});
```

But when calling that endpoint `/encode`, this results in an Error `k must be an instance of TypedArray` when using sodium to encode the data.

### Expected Behavior

The behavior I'm expecting is the same as when providing an invalid or empty Buffer/String i.e: throwing a kind of `PluginRegistrationError` when loading the plugin and not dealing with runtime errors once the plugin is registered.

For instance:

```js
fastify.register(fastifySecureSession, {
  cookieName: "session-cookie",
  key: "" // invalid because empty,
  cookie: {
    path: "/",
    maxAge: 3600,
    httpOnly: true,
  },
});
```

Doing this would result in a `key or secret must specified` error.
This would allow the library to be consistent with the way of dealing with valid/invalid keys before registering the plugin.

I would be happy to open a PR if we all agree it's not the expected behavior 😄

**Comment by mcollina** [comment]
Good spot! Go for the PR, thanks!

**Comment by antoine-coulon** [comment]
@mcollina cool, I'll land the PR soon, could you assign me to that issue so I can track that? Thanks!
