### ISSUE TITLE
"k\" must be crypto_secretbox_KEYBYTES bytes long

### ISSUE THREAD

**Issue by antoine-coulon** [fastify/fastify-secure-session#131]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hello guys, 

I have a question regarding the current assertions implemented around each **key** length.

When registering the plugin and providing a _key_, assertions about that key (or key array) require that each key is **atleast 32 bytes** long [here](https://github.com/fastify/fastify-secure-session/blob/93117ae50f2f578f5b539bd601ac4521e308ca49/index.js#L74), [here](https://github.com/fastify/fastify-secure-session/blob/93117ae50f2f578f5b539bd601ac4521e308ca49/index.js#L76) and [here](https://github.com/fastify/fastify-secure-session/blob/93117ae50f2f578f5b539bd601ac4521e308ca49/index.js#L38).

When providing for instance a key with **64 bytes**, the key is considered valid at registration time:

```javascript
// Ok
fastify.register(require('@fastify/secure-session'), {
  // 64 bytes
  key: Buffer.from('4b56344efdfd4afd0964fd27fd16877a4b56344efdfd4afd0964fd27fd16877a', 'utf-8'), 
}
```

But at runtime when creating the session, there is an error which appears to be thrown from libsodium `"k\" must be crypto_secretbox_KEYBYTES bytes long` (crypto_secretbox_KEYBYTES seems to be 32):

```javascript
// Ko
fastify.post('/', (request, reply) => {
 // runtime error mentioned above
  request.session.set('data', { payload: "hello Antoine" })
  reply.send('hello world')
})
```

I am missing something here? Or we should just constraint the _inputs keys_ to be **strictly 32 bytes long** to respect the libsodium constraint of _crypto_secretbox_KEYBYTES_ and make the registration fail if any key is not **strictly equal to 32 bytes** ?

Thanks

**Comment by mcollina** [comment]
The limit is imposed by libsodium, so it's ok to move the check upwards in our lib.
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by antoine-coulon** [comment]
For sure, I'll take care of that
