### ISSUE TITLE
salt must be length 24

### ISSUE THREAD

**Issue by wilg** [fastify/fastify-secure-session#16]
I get the error message "salt must be length 24" with a salt of length 24 (as measured by `.length` and `Buffer.byteLength()`

I checked `sodium.crypto_pwhash_SALTBYTES` on my system and it returns `16`. However, a 16 character salt still doesn't work.

**Comment by srmarjani** [comment]
Hi
How do you generate salt?

**Comment by tetchel** [comment]
it worked for me using `salt: crypto.randomBytes(16)`

**Comment by climba03003** [comment]
I think this issue can be safely closed #17
