### ISSUE TITLE
Enable multiple cookie sessions

### ISSUE THREAD

**Issue by patilanz** [fastify/fastify-secure-session#178]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

I'm using fastify-secure-session with fastify-passport like a identity provider for multiple pages. The problem is that there is only one cookieName in the configuration. Is it possible to use something like this:

```js
// before
  fastify.register(fastifySecureSession, {
    key: fs.readFileSync(path.join(__dirname, 'secret-key')),
    cookieName: global.cookie_token_name,
    // options for setCookie of fastify-cookie
    cookie: {
      path: '/',
      httpOnly: is_prod,
      signed: is_prod
    }
  });

// after
  fastify.register(fastifySecureSession, {
    key: fs.readFileSync(path.join(__dirname, 'secret-key')),
    cookies: [
      {name: global.cookie_token_name, options: {path: '/admin', httpOnly: true, secure: is_prod}},
      {name: global.cookie_token_name2, options: {path: '/', httpOnly: true, secure: is_prod}},
    ]
  });
```

**Comment by mcollina** [comment]
Why would there be more than one cookie?

**Comment by patilanz** [comment]
> 

In my case I need one cookie for www.domain.com and another for www.domain.com/path.

**Comment by mcollina** [comment]
And you need to read both at the same time?

**Comment by patilanz** [comment]
Yes, the server is responsible for both pages. Customers and Admins can have different accounts and can be authenticated at the same time.

**Comment by mcollina** [comment]
> Maybe using a different fastify context and registering the plugin two times?

Yes, you should encapsulate them separately.
