### ISSUE TITLE
Following cookie throws an uncaught exception

### ISSUE THREAD

**Issue by sreekotay** [fastify/fastify-secure-session#18]
session=96443e14-a82f-4179-63b2-b7fd67a87850

(note there is no trailing semi-colon)

**Comment by mcollina** [comment]
Can you paste a repro?

**Comment by sreekotay** [comment]
The cookie is literally that string:  "96443e14-a82f-4179-63b2-b7fd67a87850".

Not sure how or why it was set that way, but if it has no ";" boom....

The exception occurs at line 86 in index.js as nonceB64 is null (because split array has length 1).

**Comment by mcollina** [comment]
Can you please provide some code that demonstrate this? A PR that fixes the bug would also be awesome.

**Comment by sreekotay** [comment]
I can provide PR ... repro code is hard.  

Not quite sure how that cookie got set, but simply running with your fastify extension results in uncaught exception.  Literally did not even invoke the cookie yet or use it any way.  In fact, it's a client cookie.

**Comment by sreekotay** [comment]
Submitted PR

**Comment by sreekotay** [comment]
btw, this code: 
if ([SOME CONDITION) {
        // unable to decrypt
        request.session = new Session({})
        next()
        return
      }

is repeated a lot - might I suggest either try/catch or a function to better DRY

**Comment by is2ei** [comment]
Is this issue still a problem? Some PRs are provided.
- #20
- #19
