### ISSUE TITLE
Release new version to be type compatible with other `@fastify/cookie` modules

### ISSUE THREAD

**Issue by voxpelli** [fastify/fastify-secure-session#196]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Using the current latest version of this module and of `@fastify/oauth2` causes type errors as they rely on two different major versions of `@fastify/cookie`

#194 merged an update, but its yet to be released.

Releasing that as eg. `6.2.1` would be very nice 👍

**Comment by mcollina** [comment]
done as v7.0.0
