### ISSUE TITLE
Update cookie expiration without updating data

### ISSUE THREAD

**Issue by Momy93** [fastify/fastify-secure-session#197]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

A `touch()` method (like in @fastify/session) to extend to cookie expiration date, without changing the session data. 
This could be done by setting `changed=true`.

### Motivation

It's useful in scenarios where the session is extended evey time the client calls some endpoints.

### Example

Whenever we want to extend the session, we would do:

`request.session.touch();`

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
