### ISSUE TITLE
200:/-_0.,0007.00/:;(7&€€8..;9.7800000"

### ISSUE THREAD

**Issue by LeoBLMitz** [fastify/fastify-secure-session#199]
## 👮 Responsible Disclosure

Do not open issues that might have security implications. It is critical that security related issues
are reported privately so we have time to address them before they become public knowledge.

Please read our [SECURITY.md](https://github.com/fastify/.github/blob/main/SECURITY.md) before reporting a vulnerability.

Individuals who find potential vulnerabilities in a package are invited
to complete a vulnerability report on the dedicated HackerOne organization:

[https://hackerone.com/fastify](https://hackerone.com/fastify)

Vulnerabilities can also be reported by emailing to Fastify core members: 

- [Matteo Collina](mailto:matteo.collina@gmail.com)

**Comment by mcollina** [comment]
This is spam.

**Comment by mcollina** [comment]
The next one like this I see in one of the repos I maintain and I'll block you everywhere.

**Comment by jsumners** [comment]
I tried to report the content as spam on the previous one, but GH doesn't offer that in the report content feature 😕

**Comment by LeoBLMitz** [comment]
I have been hack by a girl

**Comment by LeoBLMitz** [comment]
> The next one like this I see in one of the repos I maintain and I'll block you everywhere.

I have been hack by a fucking girl
