### ISSUE TITLE
Upgrade @fastify/cookie to 9.1.0

### ISSUE THREAD

**Issue by nalanj** [fastify/fastify-secure-session#204]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.24.3

### Plugin version

7.1.0

### Node.js version

20.7.0

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

14

### Description

Right now I'm getting deprecation warnings that look like this:

```sh
(node:98534) [FSTDEP019] FastifyDeprecation: reply.context property access is deprecated. Please use "reply.routeOptions.config" or "reply.routeOptions.schema" instead for accessing Route settings. The "reply.context" will be removed in `fastify@5`.
(Use `node --trace-warnings ...` to show where the warning was created)
```

I traced it back to the fact that this plugin currently relies on `@fastify/cookie` 9.0.4, and context is no longer used in `@fastify/cookie` 9.1.0.

### Steps to Reproduce

- Use `@fastify/secure-session` 7.1.0 in a project.

### Expected Behavior

It shouldn't print a deprecation warning.

**Comment by Uzlopak** [comment]
We are not using lock files. Just delete node_modules package-lock and run again npm i.
