### ISSUE TITLE
typescript types don't work properly

### ISSUE THREAD

**Issue by Zamiell** [fastify/fastify-secure-session#211]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.25.1

### Plugin version

7.1.0

### Node.js version

20.9.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

The types don't work properly.
e.g.:

```ts
declare module "@fastify/secure-session" {
  interface SessionData {
    userID: number;
  }
}

async function login(
  request: FastifyRequest,
  reply: FastifyReply,
): Promise<FastifyReply> {
  request.session.set("usersID", 123);
}
```

In the above code snippet, we made a typo, and typed it as "usersID" instead of "userID". Oops! But we don't get a compiler error - it just works, and the bug makes its way to production.

Is there some way for a declaration merge to get rid of the string index signature? Because that's the root cause of the bug.

**Comment by mcollina** [comment]
> Is there some way for a declaration merge to get rid of the string index signature? Because that's the root cause of the bug.

Unfortunately no. I'm not sure how to fix this at all.

**Comment by Gehbt** [comment]
I have 2 proposal with demo: 
A: When `set` a mission `key`, the `value` should always be type `never`.
B: Remove indexed access type and ensured extends what type is defined.

[commit A](https://github.com/Gehbt/fastify-secure-session/commit/c3dbd876fd19c942206315fa304d1a238d1d2ee3) is base avoid `any`
[commit B](https://github.com/Gehbt/fastify-secure-session/commit/219259b84f05fd5687d110cd2576f6b76f24546d) is base remove the indexed access type

> Unfortunately no. I'm not sure how to fix this at all.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
