### ISSUE TITLE
New "expiry" is not included in TypeScript definition

### ISSUE THREAD

**Issue by joshuaavalon** [fastify/fastify-secure-session#223]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.2

### Plugin version

7.5.0

### Node.js version

20.10.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

New `expiry` options from 7.3.0 is not added to TypeScript definition

### Steps to Reproduce

See types/index.d.ts

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests. We use tsd for types tests.

**Comment by joshuaavalon** [comment]
I mainly use TypeScript for development. I am not familiar with tsd, so I won't send a pull request.
