### ISSUE TITLE
What version is compatible with Fastify 3.x? 

### ISSUE THREAD

**Issue by simkessy** [fastify/fastify-secure-session#230]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.x

### Plugin version

latest

### Node.js version

14

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

18

### Description

I'm upgrading from 2x to 3.29.5

I have:

```
    "@fastify/http-proxy": "7",
    "@fastify/request-context": "^5.1.0",
    "@fastify/secure-session": "^7.5.1",
```

Typescript returns errors about missing types: 

```
node_modules/.pnpm/@fastify+secure-session@7.5.1/node_modules/@fastify/secure-session/types/index.d.ts:3:33 - error TS2614: Module '"fastify"' has no exported member 'FastifyBaseLogger'. Did you mean to use 'import FastifyBaseLogger from "fastify"' instead?

3 import { FastifyPluginCallback, FastifyBaseLogger, FastifyInstance} from "fastify";
                                  ~~~~~~~~~~~~~~~~~

node_modules/.pnpm/@fastify+secure-session@7.5.1/node_modules/@fastify/secure-session/types/index.d.ts:12:13 - error TS2428: All declarations of 'FastifyRequest' must have identical type parameters.

12   interface FastifyRequest {
```

I'm assuming this is due to version incompatibility but I can't figure out what version is compatible with 3.29.5

**Comment by Uzlopak** [comment]
Closing in favor of https://github.com/fastify/fastify/issues/5622
