### ISSUE TITLE
What version works with Fastify 3.x? 

### ISSUE THREAD

**Issue by simkessy** [fastify/fastify-secure-session#231]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3@latest

### Plugin version

???

### Node.js version

12

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

18

### Description

I'm trying to update Fastify from 2 to 3x but I can't tell which version of this package is compatible with 3x.

**Comment by jsumners** [comment]
Please stop opening the same issue in multiple repos.
