### ISSUE TITLE
Add regenerate method / match type signature with @fastify/session

### ISSUE THREAD

**Issue by bencoder** [fastify/fastify-secure-session#233]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

`@fastify/passport` has to do some some [hacky workarounds](https://github.com/fastify/fastify-passport/blob/3542316c42a26664c49558482ac041e461ddf897/src/session-managers/SecureSessionManager.ts#L53-L54) in order to support both `@fastify/secure-session` and `@fastify/session`

it's also causing problems with typing as seen in https://github.com/fastify/fastify-passport/pull/1193

We should try to unify the types as much as possible to avoid this

**Comment by Uzlopak** [comment]
Can you provide a PR, please?
