### ISSUE TITLE
Can we consider releasing a new version

### ISSUE THREAD

**Issue by puzzle9** [fastify/fastify-secure-session#237]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

- https://github.com/fastify/fastify-secure-session/commit/fdde0517f3e16b6ad7d2be17d696e869a6bfd43e

need `regenerate`

**Comment by Eomm** [comment]
Done: https://github.com/fastify/fastify-secure-session/releases/tag/v8.1.0
