### ISSUE TITLE
Allow for custom cookie options per session

### ISSUE THREAD

**Issue by patrickmichalina** [fastify/fastify-secure-session#26]
For example: some users want their cookies to wipe after the session others want them to stick around for a week.

I think it is possible by extending the Session class and setting a new optional property that will then be referenced during the cookie response.

Would you consider this feature?

**Comment by mcollina** [comment]
Would you like to send a Pull Request to add this feature? Remember to add unit tests.

**Comment by patrickmichalina** [comment]
I plan to take this on in a couple weeks, thank you.
