### ISSUE TITLE
Log messages

### ISSUE THREAD

**Issue by real-artswan** [fastify/fastify-secure-session#32]
Could you, please, add an option to don't log messages about session setting/non-changed/removing etc?
The message "fastify-secure-session: there is no session or the session didn't change, leaving it as is" has a little sense and just flooding logs.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by real-artswan** [comment]
I'll try

**Comment by real-artswan** [comment]
BTW, I didn't see these messages before, what was the reason of adding that?

**Comment by mcollina** [comment]
I'm sorry but I don't understand.. those are debug logs. Why is it a problem in including them here?

**Comment by real-artswan** [comment]
Please take a look at PR, I`m not sure what kind of tests I can add there (btw logging is disabled at all in all existing tests).

Regarding why:
I'd like to keep my logs clean for obvious, I beleive, reasons: when something goes wrong you read the logs and the more usefull information there the better, and more usefull means less water. Settings/unsettings/removing/etc session usually not usefull, I'd like to log if session is set or isn't set  by myself in cases when I need it and when I think it is important. 
Now I have +1 line (in 99.99% of time it is just repeating line I mentioned in the first post) per each request.
So this PR aims to fix that.
If you need logs for your own debugging) why don't use own logging like https://github.com/visionmedia/debug ? I've been noticing it in many mature products and I use it in my projects - very easy to enable/disable with fine graining.

BTW, A lot of thanks for a perfect library!

**Comment by airhorns** [comment]
Why not just change the log level to something other than debug? They're written at the `debug` level so that they're only present when you want the most verbose information. I think the default log level for fastify is `info`, which would hide those logs.

**Comment by real-artswan** [comment]
> Why not just change your log level to something other than debug?
Then I'll lose request/response logs. It would be great if Fastify supported different logLevel for plugins, but, it seems, it's not going to be implemented soon (https://github.com/fastify/fastify/issues/636).

**Comment by airhorns** [comment]
Do you mean request/response bodies? Because the incoming request / request completed logs are at the info level, so if you set the log level to info you'd still see them. Also, there's a PR linked there that would get you back debug logs if you want: https://github.com/fastify/fastify/pull/639 , you'd have to set the level on each route you wanted them for which would be annoying but it's at least possible.

**Comment by real-artswan** [comment]
ok, guys, nevermind, for a while, I just set log level to "info" when it was "trace". It seems it covers all business requirements. 
Anyway (for the sake of justice), I believe, that plugins should not spoil request logs.
Also, one can disable Fasify logging and use hooks to log whatever he want (may be I'll use this approach later as it is more independent and flexible)
Cheers and close that.
