### ISSUE TITLE
Export decodeSession for libraries to use directly

### ISSUE THREAD

**Issue by cretz** [fastify/fastify-secure-session#33]
Since https://github.com/fastify/fastify-websocket/issues/70 isn't fixed, and for that and in other cases where people might want to read session info from a raw cookie value, please export `decodeSession` accepting the raw cookie payload (and no request object). Similarly for those that might want to write, `encodeSession` might have value being exposed too.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
