### ISSUE TITLE
README code snippets don't work without cookie path key

### ISSUE THREAD

**Issue by mattwaler** [fastify/fastify-secure-session#38]
## 🐛 Bug Report

In all of the snippets in the README, the configuration option when registering the plugin does not specify a path key. Without this key, the plugin does not work at all.

## To Reproduce

Copy any snippet as is into a fastify project, and sessions and cookies will not save properly.

## Expected behavior

The snippets should at least include the minimal configuration needed for the plugin to work as intended. Just adding this below to the config object to each snippet would ensure people don't get stuck for 45~ minutes like I did 👍 

Maybe it makes sense to set this as a default value if it's not passed to the plugin config as well? That's up to you guys.

```js
cookie: {
  path: '/',
}
```

**Comment by mcollina** [comment]
Good spot, thanks! Would you like to send a PR to fix them?

**Comment by mattwaler** [comment]
Sent!
