### ISSUE TITLE
Add info about using keys as hex strings in the README

### ISSUE THREAD

**Issue by PierBover** [fastify/fastify-secure-session#42]
Sometimes deploy is being made from a repo (eg: Heroku) but it's not a great idea to commit key files.

A solution to not use low entropy strings would be to convert the generated key into a hex string and then convert it to a buffer when initializing the plugin.

To convert the key from buffer to a hex string;
```
const key = fs.readFileSync(path.join(__dirname, 'secret-key'));
const hex = key.toString('hex'));
```
And then something like:
```
fastify.register(fastifySecureSession, {
  key: Buffer.from(process.env.COOKIE_KEY, 'hex'),
});
```

Would you accept a PR to add this info to the README?

**Comment by mcollina** [comment]
Definitely! Go for it!

**Comment by PierBover** [comment]
https://github.com/fastify/fastify-secure-session/pull/43
