### ISSUE TITLE
External store support

### ISSUE THREAD

**Issue by mgcrea** [fastify/fastify-secure-session#46]
## 🚀 Feature Proposal

Is external store support (eg. redis) on the roadmap?

## Motivation

Would love to try this in production but would require to store session in a shared DB.

## Example

```ts
fastify.register(require('fastify-secure-session'), {
  store: IS_TEST ? new MemoryStore() : new RedisStore({ client: new Redis(REDIS_URI), ttl: SESSION_TTL }),
})
```

**Comment by mcollina** [comment]
https://www.npmjs.com/package/fastify-session implements that.

**Comment by mgcrea** [comment]
@mcollina That's what I'm using currently but I wanted to use `fastify-passport`. So I thought it would be nice to have that here since it is required for most production environments.

**Comment by mcollina** [comment]
I would recommend to update fastify-passport to use both.

**Comment by mgcrea** [comment]
That was my other option, but went for this one due to the official `fastify` branding that gave me more confidence. Anyway will probably do that if I fail to achieve what I want with this one. Thanks 👍

**Comment by mcollina** [comment]
Yep. We might want to have it in the umbrella org :).

**Comment by vikasg603** [comment]
Hey @mcollina, The plugin satisfy-session is not updated for the last ten months, and they are using the deprecated version, so using them will not be good.

Do you have any planning of adding External store support to this plugin?

**Comment by gajus** [comment]
You may also evaluate https://github.com/mgcrea/fastify-session
