### ISSUE TITLE
\"k\" must be crypto_secretbox_KEYBYTES bytes long issue

### ISSUE THREAD

**Issue by PringlePot** [fastify/fastify-secure-session#77]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.16.1

### Plugin version

2.3.1

### Node.js version

14.16.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

Im trying to make a fastify application using passport. I found https://github.com/fastify/fastify-passport and tried to use it. For an unkown reason i get this issue `\"k\" must be crypto_secretbox_KEYBYTES bytes long` . Im posting the issue on this repository because i saw this issue https://github.com/fastify/fastify/issues/2719

### Steps to Reproduce

Im registering the session using process env (which is not the reason)

```ts
server.register(fastifySecureSesstion, {
  key: process.env.SECRET!,
});
```

After thats done I initialize passport.js, following fastify's example.

```ts
server.register(passport.initialize());
server.register(passport.secureSession());
```

In my request i set this as authentication strategy.

### Expected Behavior

I expected the request to work without error, and log me into my account.

**Comment by yaroslaviy** [comment]
Having same issue, how did you resolve it? @PringlePot

**Comment by sbolduc-cb** [comment]
I'm interested in this as I have the same issue. Did you find a solution @PringlePot in the end?

**Comment by PringlePot** [comment]
Yeah i used a pregenerated key like the readme. That works for me

**Comment by johannesspohr** [comment]
In case somebody else comes across this: For me the keys won't work when I run the code generation snippet in Powershell, but they work when using git bash or WSL. Looks like something gets weirdly encoded when the binary data is streamed to the file.

**Comment by mehdi-lafbit** [comment]
use this syntax
`
server.register(fastifySecureSession, {
    cookieName: 'usn',
    key: fs.readFileSync(join(__dirname, 'path-to/secret-key'))
})
`
