### ISSUE TITLE
Recommend way to decorate secure-session

### ISSUE THREAD

**Issue by MyTotoro** [fastify/fastify-secure-session#94]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi, I've successfully managed to integrate `fastify-passport` and `fastify-secure-session`. I'm able to make oauth calls and have the data stored through `registerUserDeserializer` and `registerUserSerializer`. I'm using this to encode user information and authentication.

I'd like to protect certain routes with secure session but I'm not sure what the best practice is, i.e.

```
routes/
....auth/ (contains index.js where secure-session is registered)
....data1/ (provides a protected resource)
....data2/ (provides a public resource)
```

I thought `fastify.register` encapsulation does not apply to children but this does not work:

```
routes/
....auth/ (contains index.js where secure-session is registered)
........data1/ (provides a protected resource)
....data2/ (provides a public resource)
```

1. `registerUserDeserializer` is not called when accessing routes in `data1/`
2.  accessing `request.session.get`, I see the following error: `Cannot read property 'get' of undefined` - which is somewhat expected if the `passport` and `secure-session` context is limited to `auth/` folder only

Is there a way to make `request.session` exposed  or structure the app?

**Comment by climba03003** [comment]
Can you provide a minimal repro for your issue? It is more straight forward to debug or find out the problem with code.

Encapsulation is creating context base on `.register`, folder structure do not affect the encapsulation.
I would recommend to register `session` plugin globally, because it is hard to determine if you have any other routes / prefix need the session.

**Comment by MyTotoro** [comment]
@climba03003 

I've posted a minimal repo generated using `fastify-cli`, hopefully you can easily reproduce what I'm seeing with a few commands:

1. `npm install`
2. `npm run dev`

the `request.session` works fine with `/auth/` and `/auth/2` routes, you can see in the log that the session data is being stored and retrieved. What I expect is that this would work across other routes / inner folder structures. In places like `/example`, I don't need the access to `session`. 

But as you said the folder structure might have no impact on this. Maybe I thought this would be similar to how `fastify-cors` would be accessible to every route?

**Comment by MyTotoro** [comment]
what documentation describes how `fastify-autoload` manages context? I'd like to properly understand whats happening

I can't see how registering `fastify-secure-session` in `context/protected` is different than my folder structure? Unless the fastify that is passed into `context/protected` routes will have context properly populated with `secure-session`?

**Comment by climba03003** [comment]
`fastify-autoload` is a plugin to help you do `.register` automatically. Unless you explicitly specified, each `.register` should create a new encapsulate context.

**Comment by MyTotoro** [comment]
I see - I read more into the documentation of `autoload`, I just moved the auth logic into a plugin and registered as a plugin across my app
